### ISSUE TITLE
Marauder without rsync

### ISSUE THREAD

**Issue by mandal-rahul** [Makeshift/Media-Compose-Stack#13]
Im not in need of remote uploads and would prefer to keep my downloads locally (Instead of uploading to gdrive or cloud)

Can i use Marauder without rclone by removing it from .yml file? Would it cause any conflicts?

**Comment by Makeshift** [comment]
I think it should work fine, yeah. You'll probably have to do config slightly differently so it downloads to whatever place you like, but I don't think it'll cause issues. Let me know how it goes!

**Comment by Makeshift** [comment]
Just a very late note for anybody coming across this issue and looking to do similar - Marauder will no longer work without rclone. All the containers in the stack make sure that the remote mount is mounted before starting, so services will not start without it.

**Comment by mistercorea** [comment]
> Just a very late note for anybody coming across this issue and looking to do similar - Marauder will no longer work without rclone. All the containers in the stack make sure that the remote mount is mounted before starting, so services will not start without it.

Can I just remove depends on rclone?
