### ISSUE TITLE
Delete files form mount?

### ISSUE THREAD

**Issue by jaannnis** [Makeshift/Media-Compose-Stack#16]
How can we delete Files that are on the mount?
Just deleting it (from either container or the host) give you:
``` 
m -rf /opt/docker/Marauder/shared/merged/Media/Movies/foo/bar.mkv
rm: cannot remove '/opt/docker/Marauder/shared/merged/Media/Movies/foo/bar.mkv': Input/output error
```
Using rclones built in delete function (inside the rclone container) gives you this:
```
Ubuntu-2204-jammy-amd64-base:/# rclone delete  shared/merged/Media/Movies/foo/bar.mkv
2023/01/08 15:21:50 ERROR : bar.mkv: Couldn't delete: remove /shared/merged/Media/Movies/foo/bar.mkv: input/output error
2023/01/08 15:21:50 ERROR : Attempt 1/3 failed with 2 errors and: failed to delete 1 files
2023/01/08 15:21:51 ERROR : Attempt 2/3 succeeded
```
But the file doesn't get deleted...
Am I overseeing anything?

**Comment by Makeshift** [comment]
This appears to be an rclone issue, as both methods should work. Have you tried restarting the rclone container to remount it? Failing that, it may also be worth trying a machine reboot, as FUSE does -weird things- sometimes.

**Comment by jaannnis** [comment]
both rclone containers were restarted multiple times and I just restarted the host to be sure, same issue.

are these mount options fine? should be rw...
 taken from the host:
```
root@Ubuntu-2204-jammy-amd64-base /opt/docker/Marauder # mount | grep shared
union: on /opt/docker/Marauder/shared_plex/plex type fuse.rclone (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
union: on /opt/docker/Marauder/shared/merged type fuse.rclone (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
```

Would you be able to help me to mount just the encrypted gdrive? I'm with you that the problem looks to be fuse related...

Then I could shut down all the containers, mount directly on the host, delete files, unmount on host, restart containers...

**Comment by Makeshift** [comment]
Very odd indeed. Those options look sane to me.

While the rclone container is running, you can run `docker cp Marauder-rclone:/root/.config/rclone/rclone.conf .` to grab a copy of the finalised rclone.conf, which you can then move to `~/.config/rclone/rclone.conf` and use it with rclone commands on your host/another machine, including mount and `rclone delete remote:path` which should hopefully work.

Let me know if you get anywhere with it, quite curious what's going on here. I've been musing about building something that doesn't use FUSE, but unfortunately it would mean essentially writing my own media server and extensive modifications to all the tools to be able to support other forms of storage...

**Comment by jaannnis** [comment]
ok, so I tried to mount the share locally, which does work (thanks for the instructions), but when I tried to delete the file rclone gives me this error (and rm the same as before), so this does look like a problem with the service accounts???

```
2023/01/08 16:39:08 ERROR : IO error: googleapi: Error 403: The user does not have sufficient permissions for this file., insufficientFilePermissions
```

I just used the "rclone_mount_download.json" as account file....

**Comment by jaannnis** [comment]
ok got it, it was a google permission issue.
I went to: [https://admin.google.com/u/1/ac/drive/manageshareddrives?hl=en_US](https://admin.google.com/u/1/ac/drive/manageshareddrives?hl=en_US)
and changed the permission of the marauders group (in which all the service accounts are) from "Content Manager" to "Manager":
![image](https://user-images.githubusercontent.com/20789461/211208945-46b56a8c-eff2-40b6-bd7f-39e67d196e82.png)


And everything works as expected.
Thanks a lot for you help and the cool containers you built!

**Comment by Makeshift** [comment]
Hmm, yeah it looks like that service account doesn't have permission to delete that specific file.

Are you able to delete other files in that drive, or are all files similarly affected? If you can add new files and edit existing files but not delete them, then I think it's because the Marauder group was added as a "Contributor" and not a "Content Manager" or "Manager". If you go to Google Drive and find your team drive, and click on the list under its name to manage permissions:
![image](https://user-images.githubusercontent.com/345013/211208930-8b5d5dd2-f408-438d-987b-8547776fab82.png)

asdhasfgadsh you beat me to it, haha nicely found!
